2023-07-15 12:09:53,890 INFO    MainThread:5137 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-15 12:09:53,890 INFO    MainThread:5137 [wandb_setup.py:_flush():76] Configure stats pid to 5137
2023-07-15 12:09:53,890 INFO    MainThread:5137 [wandb_setup.py:_flush():76] Loading settings from /home/gustavo/.config/wandb/settings
2023-07-15 12:09:53,890 INFO    MainThread:5137 [wandb_setup.py:_flush():76] Loading settings from /home/gustavo/PersonalProjects/Cat-Dogs_audio-classification/wandb/settings
2023-07-15 12:09:53,890 INFO    MainThread:5137 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-15 12:09:53,890 INFO    MainThread:5137 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-15 12:09:53,890 INFO    MainThread:5137 [wandb_init.py:_log_setup():507] Logging user logs to /home/gustavo/PersonalProjects/Cat-Dogs_audio-classification/wandb/run-20230715_120953-y7ipiv0e/logs/debug.log
2023-07-15 12:09:53,890 INFO    MainThread:5137 [wandb_init.py:_log_setup():508] Logging internal logs to /home/gustavo/PersonalProjects/Cat-Dogs_audio-classification/wandb/run-20230715_120953-y7ipiv0e/logs/debug-internal.log
2023-07-15 12:09:53,890 INFO    MainThread:5137 [wandb_init.py:init():547] calling init triggers
2023-07-15 12:09:53,890 INFO    MainThread:5137 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-15 12:09:53,890 INFO    MainThread:5137 [wandb_init.py:init():571] re-initializing run, found existing run on stack: e9uls8e0
2023-07-15 12:09:53,892 INFO    MainThread:5137 [wandb_run.py:_finish():1887] finishing run gustavoreis/CatXDogs/e9uls8e0
2023-07-15 12:09:53,892 ERROR   MainThread:5137 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2023-07-15 12:09:53,892 INFO    MainThread:5137 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-07-15 12:09:53,892 INFO    MainThread:5137 [wandb_init.py:_jupyter_teardown():435] cleaning up jupyter logic
2023-07-15 12:09:53,892 INFO    MainThread:5137 [wandb_run.py:_atexit_cleanup():2121] got exitcode: 0
2023-07-15 12:09:53,892 INFO    MainThread:5137 [wandb_run.py:_restore():2104] restore
2023-07-15 12:09:53,892 INFO    MainThread:5137 [wandb_run.py:_restore():2110] restore done
2023-07-15 12:09:57,038 INFO    MainThread:5137 [wandb_init.py:init():596] starting backend
2023-07-15 12:09:57,038 INFO    MainThread:5137 [wandb_init.py:init():600] setting up manager
2023-07-15 12:09:57,040 INFO    MainThread:5137 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-07-15 12:09:57,043 INFO    MainThread:5137 [wandb_init.py:init():606] backend started and connected
2023-07-15 12:09:57,044 INFO    MainThread:5137 [wandb_run.py:_label_probe_notebook():1233] probe notebook
2023-07-15 12:09:57,044 INFO    MainThread:5137 [wandb_run.py:_label_probe_notebook():1243] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-07-15 12:09:57,044 INFO    MainThread:5137 [wandb_init.py:init():705] updated telemetry
2023-07-15 12:09:57,084 INFO    MainThread:5137 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
